# Generated by Django 3.2.6 on 2021-09-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_cart_use_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='use_point',
        ),
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.RemoveField(
            model_name='member',
            name='m_point',
        ),
        migrations.AddField(
            model_name='company',
            name='lat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='lng',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
