# Generated by Django 3.2.6 on 2021-09-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_product_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_image_path',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
